apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell
  namespace: mfe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shell
  template:
    metadata:
      labels:
        app: shell
    spec:
      containers:
        - name: shell
          image: mfe-shell:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
